# Generated by Django 4.2.7 on 2026-04-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='books.book')),
            ],
            options={
                'unique_together': {('book', 'tag')},
            },
        ),
    ]
